DecomposeMolecule関数の追加実装
akiyamalab/restretto pull request #25
Opened 2024-07-12 00:08 UTC by smzmsys

# 内容
- フラグメント分割時に切断部分をアタッチメントポイントにするか水素原子にするか指定できる`dummy_atom`オプションの実装
- 化合物をフラグメントに分割する際に、重原子1つのみのフラグメント（孤立原子）が存在する場合は他のフラグメントに吸収する`merge_solitary`オプションの実装

# 実装
## dummy_atom
- `dummy_atom`が`true`ならアタッチメントポイント、`false`なら水素原子
  - `fraggrid_main.cc`は`true`固定
    - `DecomposeMolecule`関数のデフォルト引数で指定
  - `decompose_main.cc`は`false`固定
    - 引数ハードコーディング
    - confは未設定
## merge_solitary
- `DecomposeMolecule`関数に、孤立原子を他フラグメントに吸収する処理を追加
  - 孤立原子を隣接するフラグメントに吸収させた場合、回転可能な結合を1rad回転させたときの構造変化（RMSD）を見て吸収させても良いか判断
- `Molecule`クラスに、結合を軸にした回転処理メソッド`bondRotate`を追加
  - 環構造識別に`UnionFindTree`を用いているため、includeを追加・Makefileを修正
- `Molecule`クラスに、別MoleculeオブジェクトとのRMSDを計算するメソッド`calcRMSD`を追加

2024-07-12 00:10 UTC, smzmsys commented
追加実装によって複数の関数やメソッドを新規定義している＆includeもいくつか追記しているので、無駄な部分があればご指摘よろしくお願いいたします。

また、`dummy_atom`のconf化やデフォルトに関してもご要望ありましたらお伝えください。

2024-07-12 14:09 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +        if (united_mol.calcRMSD(test_united_mol) >= 1e-5) {
この `1e-5` について、（前述した）ベンゾニトリルで試して、少しだけ緩くしてみてください。
特に、PDBに登録されている構造なんかは理想的な構造ではないので、多少のずれがあるはずです。

https://www.rcsb.org/structure/5JNW

2024-07-12 14:12 UTC, keisuke-yanagisawa commented
dummy_atomは一回放置して、merge_solitaryだけを対象にコメント入れました（pull request分けた方がいいかもです）

2024-07-13 01:32 UTC, smzmsys commented on src/Molecule.cc
> +    if (this_gd.size() != mol_gd.size()) {
https://github.com/akiyamalab/restretto/pull/25/commits/d67c5d3c7fc5f9e3a81d3b292709e0579aff2781

修正しました。
2次元でも`==`で比較可能でした。

2024-07-13 04:59 UTC, smzmsys commented
コメントをもとに修正しました。
# 修正箇所
- 結合回転処理関数`bond_rotate()`をMoleculeToFragmentsの無名空間に定義
  - `Molecule`クラスのメソッドは削除
- `std::vector`同士の比較方法を修正
- `IsMergeable()`の実装
- H原子を端に含む結合を回転可能とみなすように修正

# 未対応
- #26 
  - mergeされ次第対応して新規pull requestする予定
- RMSD閾値の調整
  - すでにベンゼンジアゾニウムが1つのフラグメントとして出力されているため

2024-07-13 05:20 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +    // merge solitary atoms
関数が作成されていることを確認しました。

2024-07-13 06:38 UTC, keisuke-yanagisawa requested changes

2024-07-13 06:38 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +                                     bool dummy_atom) {
dummy_atomに関わる修正はほぼ全カットになると思います。

だいぶコードを読むのに手間取ったんですが、REstrettoの実装の場合は、あくまでfragdock::Moleculeの時にはXS_TYPE_DUMMYのままにすることで切断点の情報を残しておき、toOBMol() の時に初めて切断点に対する処理を行うという実装になっているようです。
従って、この時点で XSType が XS_TYPE_DUMMY でないと、その後に insert_fragment_id_to_isotope などが機能しなくなってしまいます。

2024-07-13 06:38 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +                                     bool dummy_atom) {
https://github.com/akiyamalab/restretto/blob/master/src/OBMol.cc#L116

2024-07-13 06:38 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +                                     bool dummy_atom) {
僕も98%くらいの確信度で記述しているので、誤っている点があればご指摘ください。お願いします。

2024-07-13 06:55 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +    const vector<vector<int> > prev_sets = uf.getSets();
引数を変えたことで、そもそも必要無くなった気がします…

2024-07-13 06:58 UTC, keisuke-yanagisawa requested changes

2024-07-13 06:58 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +  Molecule gen_new_mol(const Molecule& mol, const std::vector<int>& id_map) {
意味合いからすると、 `extract_substructure` ですかね？

2024-07-16 13:29 UTC, smzmsys commented
コメントをもとに修正しました。
# 修正箇所
- `IsMergeable()`の引数変更
  - UnionFindTreeを関数内で使わず、該当フラグメントの原子IDリストを渡すように変更
  - （言い訳：`UnionFindTree::getSets()`のインデックスがIDに対応していると勘違いをしていたため、修正が遅れました…）
- dummy_atomオプションの削除
  - おっしゃる通り、`toOBMol()`で`XS_TYPE_DUMMY`が必要でした。
- ご指摘に沿って、関数名やコメント、helpなどを修正

# 未対応
- #26 
  - mergeされ次第対応して新規pull requestする予定

2024-07-18 00:43 UTC, keisuke-yanagisawa requested changes
それなりに実装が収束してきたと思います。少し細かい修正点を記述したので、対応お願いいたします。

2024-07-18 00:43 UTC, keisuke-yanagisawa commented on src/Molecule.cc
> +    translate(pos - getCenter());
baseでtranslateをするのはユーザ側が頑張る、というのが方針のようなので、`const Vector3d& base` は削除でお願いします。（それでも、以下の1例しかないんですけどね…）

https://github.com/akiyamalab/restretto/blob/master/src/Optimizer.cc#L27-L31

2024-07-18 00:43 UTC, keisuke-yanagisawa commented on src/Molecule.cc
> +  }
2か所に実際の動作が書かれていると、片方を書き換えた時に不整合が発生する可能性があります。
そのため、限定的な関数は、より汎用的な同一の関数を使うことで、実際の動作を1か所に集約させた方が良いです。
```cpp
void Molecule::axisRotate(const Vector3d &axis, fltype th){
  std::vector<int> id_set = ....
  axisRotate(axis, th, id_set);
}
```

2024-07-18 00:43 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +      exit(1);
エラーについては全て `throw ....` で例外を発出させましょう。

2024-07-18 00:43 UTC, keisuke-yanagisawa commented on src/MoleculeToFragments.cc
> +      exit(1);
`throw` であれば、ユーザ側がこれを無視しても良いか判断することができますが、`exit()` だとユーザ側は何もできなくなってしまいます。

2024-07-18 08:54 UTC, smzmsys commented
コメント通りの修正を行いました。
実行結果が変化なしであることは確認済みです。

2024-07-19 06:10 UTC, keisuke-yanagisawa approved these changes

2024-07-19 06:11 UTC, merged

2024-07-19 06:11 UTC, keisuke-yanagisawa commented
全て確認し、mainブランチにmergeしました。ありがとうございました。